apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
  labels:
    platform.agentic.io/component: istio
---
apiVersion: v1
kind: Namespace
metadata:
  name: agentgateway-system
  labels:
    platform.agentic.io/component: agentgateway
    platform.agentic.io/gateway-discovery: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: kagent-system
  labels:
    platform.agentic.io/component: kagent
    platform.agentic.io/gateway-discovery: "true"
    istio.io/dataplane-mode: ambient
---
apiVersion: v1
kind: Namespace
metadata:
  name: langfuse
  labels:
    platform.agentic.io/component: langfuse
    istio.io/dataplane-mode: ambient
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    platform.agentic.io/component: monitoring
    istio.io/dataplane-mode: ambient
---
apiVersion: v1
kind: Namespace
metadata:
  name: keycloak
  labels:
    platform.agentic.io/component: keycloak
---
apiVersion: v1
kind: Namespace
metadata:
  name: agentregistry
  labels:
    platform.agentic.io/component: agentregistry
    platform.agentic.io/gateway-discovery: "true"
    istio.io/dataplane-mode: ambient
---
apiVersion: v1
kind: Namespace
metadata:
  name: evermemos
  labels:
    platform.agentic.io/component: evermemos
    istio.io/dataplane-mode: ambient
